travis:
  secure:
    BINSTAR_TOKEN: cZfdhrH0/IzYdQ/Wucj7lkFHDYMzoJnI9J1qwpAhcO5fXY4iEo5r7vamCWAEBHbyoH1DaYJLPbVlsgGuMX9x1fx1w0Mn4Sabg5ktvtsLXRZaEsYIwKsTJN34W6ZE3ou97z6Ue+K5OuyDDXZOFpysoXYq+84fG4VVWZWL19Y253xz0YhQlb/Dd4QOxuUtx6xWS10uKruXu+NahJFsC142Rg77cUFUSjf+zYo0+bBkT/rb3rZqLyfRvYejkujlBpK//aAw3UB4AnUEEepJSAT1zbsQHfFtRs4j5kFzrV22OH5aTZA80RFuJUWqbO/M1FcV5aFML2KlCsRzCg3jN83tSigUEoTmcx0HlK4s5gI3YPX7/+mujNEvK2nheqIefsHssHGuZ/njf2NO8gm6Ti8iegR1ZEyW/1xD7PmaaHdKT/KeYof0VzijkjJAeSmtap12ZNy/BqoMgycwmscEzDsdC58uYr9TOTu9r5KxNJdJDcKECqESnYZZo28/l143vPSiOU76W5rm01f8nNTIt7KWyGEJYapSntkYepqq3BB5PyuwdYSF+uWh9HKzT5bg+cL6zm2Y+/slV+PA1fVUr9cRWsNv9Ul4yJ2EYym6f/ZvaOodjnrDhXXaAxKA3/GwGNfx5HupBV/ChpY1gZXMmAf607t+yjm+1ECl8RC2gTSQuk8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
